### ISSUE TITLE
Automatic qoutes(single/double) escape is necessary

### ISSUE THREAD

**Issue by jyotirmaybarman** [DCsunset/markdown-it-code-copy#3]
![Screenshot from 2021-09-27 10-48-20](https://user-images.githubusercontent.com/56916274/134849465-814ff1e8-c2b9-4d08-9d92-8d29180008f7.png)

**Comment by DCsunset** [comment]
Thanks for your feedback. I have fixed this bug in `v0.1.1`.
Feel free to reopen this issue if it still exists.
