### ISSUE TITLE
Custom SVG

### ISSUE THREAD

**Issue by mrleblanc101** [DCsunset/markdown-it-code-copy#7]
I'd love to use this without loading a custom icon-font.
It would be nice to be able to provide the markup directly.

**Comment by DCsunset** [comment]
I've added custom element support in the latest master branch. Feel free to test it when you have time.

**Comment by mrleblanc101** [comment]
Thanks !
I was able to make what I wanted.
Any plan on releasing a new tag ?

**Comment by DCsunset** [comment]
I just published a new version. Closing it as resolved.
